#決り文句
AllCops:
#１行あたりの文字数をチェックする
  Layout/LineLength:
    Max: 130

#指定ファイルはチェックの対象から外す
  Exclude:
  - "Rakefile"
  - "spec/rails_helper.rb"
  - "spec/spec_helper.rb"

#RSpecは一つのブロックあたりの行数が多くなるため、チェックの除外から外す
  Metrics/BlockLength:
    Exclude:
      "spec/**/*"