#決り文句
AllCops:
#１行あたりの文字数をチェックする
  Layout/LineLength:
    Max: 130

#指定ファイルはチェックの対象から外す
  Exclude:
  - "Rakefile"
  - "spec/rails_helper.rb"
  - "spec/spec_helper.rb"

#RSpecは一つのブロックあたりの行数が多くなるため、チェックの除外から外す
#ブロック内の行数をチェックする
  Metrics/BlockLength:
    Exclude:
      "spec/**/*"

#rubocopが計算して基準値を超えると警告を出す（上記頭文字をとって’Abc’）
  Metrics/AbcSize:
    Max: 50

#ifやforを使いすぎて複雑になっていないかチェックする
  Metrics/CyclomaticComplexity:
    Max: 10

#メソッド内が複雑すぎるかチェックする
  Metrics/PerceivedComplexity:
    Max: 8

#メソッドの行数の最大値を設定
  Metrics/MethodLength:
    Max: 30

#ネストの最大数を設定
  Metrics/BlockNesting:
    Max: 5