#決り文句
AllCops:
#１行あたりの文字数をチェックする
  Layout/LineLength:
    Max: 130

#指定ファイルはチェックの対象から外す
  Exclude:
  - "Rakefile"
  - "spec/rails_helper.rb"
  - "spec/spec_helper.rb"

#RSpecは一つのブロックあたりの行数が多くなるため、チェックの除外から外す
#ブロック内の行数をチェックする
  Metrics/BlockLength:
    Exclude:
      "spec/**/*"

#rubocopが計算して基準値を超えると警告を出す（上記頭文字をとって’Abc’）
  Metrics/AbcSize:
    Max: 50

