#決り文句
AllCops:
#１行あたりの文字数をチェックする
  Layout/LineLength:
    Max: 130

#指定ファイルはチェックの対象から外す
  Exclude:
  - "Rakefile"
  - "spec/rails_helper.rb"
  - "spec/spec_helper.rb"

#RSpecは一つのブロックあたりの行数が多くなるため、チェックの除外から外す
#ブロック内の行数をチェックする
  Metrics/BlockLength:
    Exclude:
      "spec/**/*"

#rubocopが計算して基準値を超えると警告を出す（上記頭文字をとって’Abc’）
  Metrics/AbcSize:
    Max: 50

#ifやforを使いすぎて複雑になっていないかチェックする
  Metrics/CyclomaticComplexity:
    Max: 10

#メソッド内が複雑すぎるかチェックする
  Metrics/PerceivedComplexity:
    Max: 8

#メソッドの行数の最大値を設定
  Metrics/MethodLength:
    Max: 30

#ネストの最大数を設定
  Metrics/BlockNesting:
    Max: 5

#クラスの行数のチェックを無効にする
  Metrics/ClassLength:
    Enabled: false

#クラス内のクラスが定義されていないかチェックする（<div class= ></div>は無効
  Style/ClassAndModuleChildren:
    Enabled: false

#空メソッドの場合、１行のスタイルにしない。（app/controllers/0000.rbのdef アクション名 endという形は無効）
  Style/EmptyMethod:
    EnforcesStyle: expanded

#日本語のコメントを許可
  Style/AsciiComments:
    Enabled: false

#クラスやモジュールの定義前に、それらの説明書きがあるかチェックする
  Style/Documentation:
    Enabled: false

